# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{valerii}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ariejan de Vroom"]
  s.date = %q{2009-09-03}
  s.description = %q{Convert integers to short strings and vice versa.}
  s.email = %q{ariejan@ariejan.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc.markdown"
  ]
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/valerii.rb",
     "test/test_helper.rb",
     "test/test_valerii.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/ariejan/valerii}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Convert integers to short strings and vice versa.}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_valerii.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
